bridge:
  domain: "localhost"
  homeserverUrl: "http://localhost:8008"
  userPrefix: "_purple_"

purple:
  backend: "node-purple" # For selecting a specific backend. One of "node-purple", "xmpp.js". Defaults to "node-purple"
  enableDebug: false
  pluginDir: "./node_modules/node-purple/deps/libpurple/"

portals:
  aliases:
    # For auto selecting the conference server
    "/^([A-Za-z0-9]+)$/":
      protocol: "prpl-jabber"
      properties:
        room: "regex:1"
        server: "conf.localhost"
    "/([A-Za-z0-9]+)/":
      protocol: "prpl-jabber"
      properties:
        conf: ""

autoRegistration:
   enabled: false
## For reference, this is how to autoregister folks with prosody (xmpp)
## with the included lua script in extras.
#   protocolSteps:
#       prpl-jabber:
#           type: "http"
#           path: "http://localhost:5280/register_account/"
#           opts:
#               method: "post"
#               usernameResult: null
#           parameters:
#               username: "m_<T_LOCALPART>"
#               nick: "<T_DISPLAYNAME>"
#               password: "<T_GENERATEPWD>"
#               auth_token: "bridge-token"
#               ip: "127.0.0.1"
#           paramsToStore:
#               - password
