bridge:
  domain: "localhost"
  homeserverUrl: "http://localhost:8008"
  userPrefix: "_purple_"

purple:
  enableDebug: false
  pluginDir: "./node_modules/node-purple/deps/libpurple/"

autoRegistration:
  enabled: true
  xmpp-url: http://localhost:5280/
